import {strict as assert} from 'node:assert';
import {LiveAudioEngine,groupPitches} from './src/live-audio.js';
let nodes=0,starts=0;
const parameter=()=>({value:0,cancelScheduledValues(){},setTargetAtTime(value){this.value=value;}});
const node=()=>{nodes++;return {gain:parameter(),frequency:parameter(),connect(target){return target;},start(){starts++;}};};
const context={currentTime:0,sampleRate:48000,createGain:node,createOscillator:node};
const engine=new LiveAudioEngine(context,{},64);
assert.equal(nodes,128);assert.equal(starts,64);
const initialNodes=nodes;
for(let tick=0;tick<1000;tick++){
    context.currentTime=tick*.02;
    engine.update(Array.from({length:782},(_,id)=>({id:tick*1000+id,frequency:73+id})));
    assert.ok(engine.active<=64);assert.equal(engine.represented,782);
    assert.equal(nodes,initialNodes);
}
const windowEdges=Array.from({length:80},(_,id)=>({id,frequency:330}));
const scene=[...windowEdges,{id:81,frequency:1174}];
engine.update(scene);
assert.equal(engine.active,2);assert.equal(engine.represented,81);assert.equal(engine.merged,79);
const middle=engine.pool.find(v=>Math.abs(v.oscillator.frequency.value-330)<1e-6);
const top=engine.pool.find(v=>Math.abs(v.oscillator.frequency.value-1174)<1e-6);
assert.ok(middle.gain.gain.value>top.gain.gain.value*8);
const groups=groupPitches(Array.from({length:5000},(_,id)=>({id,frequency:73*2**(id/5000*4)})),256);
assert.ok(groups.groups.length<=256);assert.equal(groups.groups.reduce((n,g)=>n+g.count,0),5000);
engine.setWaveform('sawtooth');engine.update(scene);
assert.ok(engine.pool.every(v=>v.oscillator.type==='sawtooth'));
engine.update([{id:1,frequency:440},{id:2,frequency:880},{id:3,frequency:30000}]);
assert.equal(engine.active,2);assert.equal(engine.outOfRange,1);assert.equal(engine.represented,2);
engine.silence();assert.equal(engine.active,0);assert.ok(engine.pool.every(v=>v.gain.gain.value===0));
engine.setWaveform('sine');engine.update([{id:4,frequency:294}]);
assert.equal(engine.active,1);assert.equal(nodes,initialNodes);
console.log('Audio pool stays bounded; all 5,000 dense edges contribute; window density outweighs a lone top edge; both waveforms and resume work.');
