import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {collectPlayableEdges} from './model-edges.js';
import {axisNames,swapAssignment,parseDuration,frequency,eventFor} from './mapping.js';
const $=id=>document.getElementById(id),status=text=>$('status').textContent=text;
let axes=['TIME','PITCH','TIMBRE'],manual=false,duration=60,half=.03,edges=[],box=new THREE.Box3(),events=[],playing=false,offset=0,started=0,ctx,master,voices=[],edgeLines,activeLines,plane,loadGeneration=0;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x111111);
const camera=new THREE.PerspectiveCamera(45,1,.01,10000),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('view').append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
const visual=new THREE.Group();scene.add(visual);
const loader=new GLTFLoader();
function dispose(root){root.traverse(o=>{o.geometry?.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];for(const m of ms){if(!m)continue;for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}});}
function fit(){const size=box.getSize(new THREE.Vector3()).length()||1;controls.target.set(0,0,0);camera.position.set(size*.85,size*.6,size*.95);camera.near=Math.max(size/10000,.000001);camera.far=size*100;camera.updateProjectionMatrix();controls.update();}
function rebuild(){stop(false);const pk=axisNames[axes.indexOf('PITCH')],span=box.max[pk]-box.min[pk];if(!manual){half=span>0?span/100:1;$('half').value=Number(half.toPrecision(8));}events=edges.map(e=>eventFor(e,axes,box,duration));document.querySelectorAll('[data-axis]').forEach(s=>s.value=axes[+s.dataset.axis]);$('axesnote').textContent=axes.map((a,i)=>`${axisNames[i].toUpperCase()} / ${a}`).join('\n');if(plane){visual.remove(plane);dispose(plane);}const k=axisNames[axes.indexOf('TIME')],others=axisNames.filter(a=>a!==k),size=box.getSize(new THREE.Vector3());const w=Math.max(size[others[0]]*1.2,size.length()*.1),h=Math.max(size[others[1]]*1.2,size.length()*.1);plane=new THREE.Group();const geo=new THREE.PlaneGeometry(k === 'x' ? h : w, k === 'x' ? w : h);plane.add(new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.065,side:THREE.DoubleSide,depthWrite:false})));plane.add(new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:0xaaaaaa,transparent:true,opacity:.7})));if(k==='x')plane.rotation.y=Math.PI/2;if(k==='y')plane.rotation.x=-Math.PI/2;visual.add(plane);status(span>0?'Ready · Playで走査を開始します。':'Pitch軸の幅が0のため、半音距離は暫定1 unitです。');}
function setModel(root,name){root.updateMatrixWorld(true);const extracted=collectPlayableEdges(root).segments;const bounds=new THREE.Box3().setFromObject(root);dispose(root);if(!extracted.length||bounds.isEmpty())throw Error('発音可能なエッジがありません。');if(extracted.length>100000)throw Error('エッジが100,000本を超えています。モデルを簡略化してください。');for(const e of extracted)for(const v of [e.a,e.b])if(![v.x,v.y,v.z].every(Number.isFinite))throw Error('座標が不正です。');stop(false);dispose(visual);visual.clear();plane=null;box.copy(bounds);edges=extracted;const center=box.getCenter(new THREE.Vector3()),points=edges.flatMap(e=>[e.a.clone().sub(center),e.b.clone().sub(center)]);edgeLines=new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0xaaaaaa,transparent:true,opacity:.65}));visual.add(edgeLines);activeLines=new THREE.LineSegments(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xffffff}));visual.add(activeLines);manual=false;$('model').textContent=name;$('stats').textContent=`${edges.length.toLocaleString()} edges · ${box.getSize(new THREE.Vector3()).toArray().map(x=>Number(x.toPrecision(4))).join(' × ')} units`;rebuild();fit();}
function demo(){loadGeneration++;const root=new THREE.Group();for(let i=0;i<7;i++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.65,.35+i*.12,.6),new THREE.MeshBasicMaterial());mesh.position.set(i*.8,i*.14,Math.sin(i*.8)*.65);mesh.rotation.z=i*.09;root.add(mesh);}setModel(root,'Study 01');}
async function load(file){if(!file||!file.name.toLowerCase().endsWith('.glb')){status('.glb ファイルを選択してください。');return;}const generation=++loadGeneration;stop(false);status('モデルを読み込んでいます…');try{if(file.size>100*1024*1024)throw Error('100 MB以下のモデルを選択してください。');const data=await file.arrayBuffer(),gltf=await loader.parseAsync(data,'');if(generation!==loadGeneration){dispose(gltf.scene);return;}setModel(gltf.scene,file.name);}catch(e){if(generation===loadGeneration)status(`読込エラー: ${e.message} 圧縮のない、データ埋込済みGLBをお試しください。`);}}
function time(){return playing?Math.min(duration,offset+(ctx.currentTime-started)):offset;}
function silence(){if(!ctx)return;const now=ctx.currentTime;for(const v of voices){v.gain.gain.cancelScheduledValues(now);v.gain.gain.setTargetAtTime(0,now,.005);for(const o of v.osc){try{o.stop(now+.03);}catch{}}}voices=[];}
function stop(reset=true){offset=reset?0:time();playing=false;silence();$('play').textContent='▶ Play';}
async function audio(){if(!ctx){ctx=new AudioContext();master=ctx.createGain();const compressor=ctx.createDynamicsCompressor();master.connect(compressor);compressor.connect(ctx.destination);}await ctx.resume();master.gain.value=+$('volume').value;}
function schedule(from){silence();const now=ctx.currentTime,pk=axisNames[axes.indexOf('PITCH')],ck=axisNames[axes.indexOf('TIMBRE')],cspan=box.max[ck]-box.min[ck],limit=ctx.sampleRate*.45;let skipped=0,occupied=[];for(const e of [...events].sort((a,b)=>a.start-b.start)){if(e.end<=from)continue;const begin=Math.max(from,e.start),u=(begin-e.start)/(e.end-e.start),coord=e.a[e.p]+(e.b[e.p]-e.a[e.p])*u,f0=frequency(coord,box.min[pk],half),f1=frequency(e.b[e.p],box.min[pk],half);if(!Number.isFinite(f0)||!Number.isFinite(f1)||Math.min(f0,f1)>=limit){skipped++;continue;}occupied=occupied.filter(t=>t>begin);if(occupied.length>=64){skipped++;continue;}occupied.push(e.end);const t0=now+begin-from+.02,t1=now+e.end-from+.02,gain=ctx.createGain(),sine=ctx.createOscillator(),rich=ctx.createOscillator(),sg=ctx.createGain(),rg=ctx.createGain();sine.type='sine';rich.type='sawtooth';const c0=cspan>0?(e.a[e.c]+(e.b[e.c]-e.a[e.c])*u-box.min[ck])/cspan:0,c1=cspan>0?(e.b[e.c]-box.min[ck])/cspan:0;for(const o of [sine,rich]){o.frequency.setValueAtTime(Math.min(limit,f0),t0);o.frequency.exponentialRampToValueAtTime(Math.min(limit,f1),t1);o.start(t0);o.stop(t1+.025);}sg.gain.setValueAtTime(1-c0,t0);sg.gain.linearRampToValueAtTime(1-c1,t1);rg.gain.setValueAtTime(c0*.35,t0);rg.gain.linearRampToValueAtTime(c1*.35,t1);sine.connect(sg).connect(gain);rich.connect(rg).connect(gain);gain.connect(master);gain.gain.setValueAtTime(0,t0);gain.gain.linearRampToValueAtTime(.06,t0+Math.min(.008,(t1-t0)/3));gain.gain.setValueAtTime(.06,Math.max(t0+.008,t1-.012));gain.gain.linearRampToValueAtTime(0,t1+.02);const voice={gain,osc:[sine,rich]};voices.push(voice);rich.onended=()=>{for(const node of [gain,sine,rich,sg,rg])node.disconnect();voices=voices.filter(v=>v!==voice);};}status(skipped?`再生中 · ${skipped}本は周波数上限／同時64音の制限で省略。`:'再生中');}
$('play').onclick=async()=>{if(playing){stop(false);return;}if(!edges.length)return;try{await audio();if(offset>=duration)offset=0;started=ctx.currentTime;schedule(offset);playing=true;$('play').textContent='Ⅱ Pause';}catch(e){status(`音声を開始できません: ${e.message}`);}};
$('stop').onclick=()=>stop();$('volume').oninput=()=>{if(master)master.gain.setTargetAtTime(+$('volume').value,ctx.currentTime,.02);};
$('seek').oninput=()=>{const was=playing;stop(false);offset=+$('seek').value*duration;if(was){started=ctx.currentTime;schedule(offset);playing=true;$('play').textContent='Ⅱ Pause';}};
$('duration').oninput=()=>{const d=parseDuration($('duration').value);if(Number.isFinite(d)&&d<=3600){stop();duration=d;rebuild();}};
$('duration').onchange=()=>{const d=parseDuration($('duration').value);if(!Number.isFinite(d)||d>3600){status('Durationは0秒より大きく60分以下で指定してください（例 1:00）。');$('duration').value=format(duration);return;}duration=d;stop();rebuild();};
$('half').oninput=()=>{const n=+$('half').value;if(Number.isFinite(n)&&n>0){half=n;manual=true;}};
$('half').onchange=()=>{const n=+$('half').value;if(!Number.isFinite(n)||n<=0){status('Half toneには0より大きい数値を入力してください。');$('half').value=half;return;}half=n;manual=true;rebuild();};$('auto').onclick=()=>{manual=false;rebuild();};
document.querySelectorAll('[data-axis]').forEach(s=>{for(const role of axes)s.add(new Option(role,role));s.onchange=()=>{axes=swapAssignment(axes,+s.dataset.axis,s.value);rebuild();};});
$('load').onclick=()=>$('file').click();$('file').onchange=()=>{load($('file').files[0]);$('file').value='';};$('demo').onclick=demo;$('fit').onclick=fit;
for(const type of ['dragover','dragleave','drop'])document.addEventListener(type,e=>{e.preventDefault();document.body.classList.toggle('drag',type==='dragover');if(type==='drop')load(e.dataTransfer.files[0]);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)stop(false);});
function format(t){return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
new ResizeObserver(()=>{const {width,height}=$('view').getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();}).observe($('view'));
function animate(){requestAnimationFrame(animate);const t=time();if(playing&&t>=duration){stop(false);status('走査が終了しました。');}if(plane){const k=axisNames[axes.indexOf('TIME')],center=box.getCenter(new THREE.Vector3());plane.position.set(0,0,0);plane.position[k]=box.min[k]+(box.max[k]-box.min[k])*t/duration-center[k];const active=playing?events.filter(e=>t>=e.start&&t<e.end):[];activeLines.geometry.dispose();activeLines.geometry=new THREE.BufferGeometry().setFromPoints(active.flatMap(e=>[e.a.clone().sub(center),e.b.clone().sub(center)]));$('voices').textContent=`${active.length} edges`;}if(document.activeElement!==$('seek'))$('seek').value=t/duration;$('clock').textContent=`${format(t)} / ${format(duration)}`;controls.update();renderer.render(scene,camera);}
try{demo();animate();}catch(e){status(`初期化エラー: ${e.message}`);}

